version: '3.7'

services:
    nginx:
        image: nginx:1.23.2-alpine
        ports:
        - '8899:8899'
        depends_on:
            - app
        volumes: 
            - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    app:
        stdin_open: true
        tty: true
        ports:
        - '3000:3000'
        build:
            target: builder
            context: .
        volumes:
            - ./public:/public
            - ./src:/src
        environment: 
            - CHOKIDAR_USEPOLLING=true
        command: npm run start